### ISSUE TITLE
USFM -> USX3: Invalid content was found starting with element 'note'

### ISSUE THREAD

**Issue by shadow-light** [schierlm/BibleMultiConverter#101] opened 2024-12-27 05:30 UTC
The following syntax throws an error:

`\f + \fr 1:1 \ft \xt 2 Kings 15.1–7; 15.32—16.20; 18.1—20.21; 2 Chronicles 26.1—32.33\f*`

```
SAXParseException; lineNumber: 0; columnNumber: 0; cvc-complex-type.2.4.a: Invalid content was found starting with element 'note'. One of '{char}' is expected.
```

I assume to be valid it would need to be contained in an `\x`, or remove the `\xt` and not markup cross-references in footnotes?

Either way, was wondering whether you'd want to just ignore the `\xt` rather than fail the conversion. But I can easily correct this file either way.

[isa.usfm.txt](https://github.com/user-attachments/files/18257679/isa.usfm.txt)

**Comment by schierlm** [comment] 2024-12-27 14:09
Thanks for reporting this issue and trying to determine the root cause. In fact, the root cause why `isa.usfm` does not convert is this construct in verse 9:7: `\fe + \fr 9:7 \ft “throne” kamenyime, “kore king kahyerrkan”\f*` A footnote (endnote) which is closed by `\f*` instead of `\fe*`. Current heuristics try to skip the unknown `\f*` end tag and issue a warning for it. As a result, the whole rest of that verse is interpreted as footnote content, including the `\x` at the end of the verse. The validation error happens because footnotes cannot contain other notes like `\x`.

I don't see a simple fix for this other than rewrite the missing end tag heuristics, where I deem the risk of adding more bugs higher than the benefits.

So I will not fix this issue, instead ask you to fix the two `\fe` tags that both are closed by `\f*`.

**Closed by schierlm** 2024-12-27 14:09 UTC
